### ISSUE TITLE
Wrong filename in upgrade docs

### ISSUE THREAD

**Issue by edbizarro** [laravel-zero/website#11]
Hi Nuno!

I'm working again on my package and start to migrate from 4.x to 5.6 and notice that [in the docs](https://github.com/laravel-zero/website/blob/gh-pages/upgrade.md#the-appphp-file) you mention the `app.php` file, but version 4 uses a file called `config.php`

After renaming that class and update the content with the new `app.php` structure the migration works like a charm!

**Comment by nunomaduro** [comment]
Hey @edbizarro! The version 4.X uses app.php. You are making a confusion with the version 3.X uses the config.php.

Thanks anyway.
