### ISSUE TITLE
Clarification about the relation to laravel and laravel-framework

### ISSUE THREAD

**Issue by wowcut** [laravel-zero/website#16]
It would be very helpful to better understand how this code relates to [Laravel](https://github.com/laravel/laravel) and the [Laravel Framework](https://github.com/laravel/framework). I was very confused by this and many questions came up: 
* If it is "based on top" of Laravel components, why does laravel-zero-framework exist? 
* Is this a fork?
* Why isn´t this a Laravel [package](https://laravel.com/docs/master/packages)? 
* Are there things that make it incompatible with Laravel?
* Can I use this in an existing Laravel app or the other way around?
* What is the difference to [laravel-console-menu](https://github.com/nunomaduro/laravel-console-menu.git)?

A few sentences about the general design would be really helpful to better understand the decisions made. Especially I wonder about how I could make this usable within an Laravel app. I have some features that I would like to make available via a Web UI **and** via console - from what I understand right now this means I have to duplicate code to achieve this, no way to have **one** project with a GUI generated by Laravel **and** a nice console menu generated by Laravel Zero? 

Thanks again for your attention.

**Comment by nunomaduro** [comment]
I am fine with the current description: https://laravel-zero.com/docs/introduction.
